apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: ashok
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: caannamalai/api-gateway:3.2.4
          ports:
            - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: ashok
  labels:
    app: apigateway
spec:
  type: LoadBalancer
  ports:
    - port: 9898
      targetPort: 9898
  selector:
    app: apigateway
